### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by keytee** [hawaii-desktop/qt5-qpa-imx6-plugin#1]
On debian, with QT 5.3.2, i got the following error:

root@imx6:~/qt5-qpa-imx6-plugin/imx6# make
/usr/lib/arm-linux-gnueabihf/qt5/bin/moc -DMESA_EGL_NO_X11_HEADERS -DQ_FONTCONFIGDATABASE -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_PLATFORMSUPPORT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/root/qt5-qpa-imx6-plugin/imx6 -I/root/qt5-qpa-imx6-plugin/imx6 -I/root/qt5-qpa-imx6-plugin/imx6 -I/opt/fsl/include -I/usr/include/libdrm -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtPlatformSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtPlatformSupport/5.3.2 -I/usr/include/arm-linux-gnueabihf/qt5/QtPlatformSupport/5.3.2/QtPlatformSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtGui/5.3.2 -I/usr/include/arm-linux-gnueabihf/qt5/QtGui/5.3.2/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore/5.3.2 -I/usr/include/arm-linux-gnueabihf/qt5/QtCore/5.3.2/QtCore -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/arm-linux-gnueabihf/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include main.cpp -o .moc/main.moc
g++ -c -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -march=armv7-a -mfpu=neon -DLINUX=1 -DEGL_API_FB=1 -O2 -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -fno-exceptions -Wall -W -D_REENTRANT -fPIC -DMESA_EGL_NO_X11_HEADERS -DQ_FONTCONFIGDATABASE -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_PLATFORMSUPPORT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I. -I. -I. -I/opt/fsl/include -isystem /usr/include/libdrm -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtPlatformSupport -isystem /usr/include/arm-linux-gnueabihf/qt5/QtPlatformSupport/5.3.2 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtPlatformSupport/5.3.2/QtPlatformSupport -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui/5.3.2 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui/5.3.2/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore/5.3.2 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore/5.3.2/QtCore -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I.moc -isystem /usr/include -o .obj/main.o main.cpp
In file included from main.cpp:35:0:
qeglfsintegration.h:59:26: error: 'QEGLPlatformContext* QEglFSIntegration::createContext(const QSurfaceFormat&, QPlatformOpenGLContext*, EGLDisplay, QVariant*) const' marked override, but does not override
     QEGLPlatformContext *createContext(const QSurfaceFormat &format,
                          ^
main.cpp: In member function 'virtual QPlatformIntegration* QEglFSIntegrationPlugin::create(const QString&, const QStringList&)':
main.cpp:51:20: error: invalid new-expression of abstract class type 'QEglFSIntegration'
         return new QEglFSIntegration;
                    ^
In file included from main.cpp:35:0:
qeglfsintegration.h:43:7: note:   because the following virtual functions are pure within 'QEglFSIntegration':
 class QEglFSIntegration : public QEGLPlatformIntegration
       ^
In file included from qeglfsintegration.h:37:0,
                 from main.cpp:35:
/usr/include/arm-linux-gnueabihf/qt5/QtPlatformSupport/5.3.2/QtPlatformSupport/private/qeglplatformintegration_p.h:89:34: note: 	virtual QEGLPlatformContext* QEGLPlatformIntegration::createContext(const QSurfaceFormat&, QPlatformOpenGLContext*, EGLDisplay) const
     virtual QEGLPlatformContext *createContext(const QSurfaceFormat &format,
                                  ^
Makefile:357: recipe for target '.obj/main.o' failed
make: *** [.obj/main.o] Error 1

What can be wrong? 

Thanks,

Tibor

**Comment by plfiorini** [comment]
This repo is very old and unmaintained. It was handy on general purpose distros that do not build Qt hardware integration modules but nowadays the Liri OS compositor has iMX 6 EGL integration in its own repository now (see https://github.com/lirios/wayland) and I'm no longer maintaining this.
